// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDenvvHdM3dGRxHFl7dMMf8UchpxyQ1ROc',
    appId: '1:707266350333:web:4d9b9791def4b15bbdc294',
    messagingSenderId: '707266350333',
    projectId: 'marketapp-3f58d',
    authDomain: 'marketapp-3f58d.firebaseapp.com',
    storageBucket: 'marketapp-3f58d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkPIJZmARXndJh4SOlPGnUpYEAxyl2lH4',
    appId: '1:707266350333:android:84b14f3aebcd6b4bbdc294',
    messagingSenderId: '707266350333',
    projectId: 'marketapp-3f58d',
    storageBucket: 'marketapp-3f58d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvxVJyzCKf4nAEQ7rHArHJnEdLfx3KsOg',
    appId: '1:707266350333:ios:854db7dabecf233bbdc294',
    messagingSenderId: '707266350333',
    projectId: 'marketapp-3f58d',
    storageBucket: 'marketapp-3f58d.appspot.com',
    androidClientId: '707266350333-gr36kievre56dg23cfji6gccg56ah10g.apps.googleusercontent.com',
    iosClientId: '707266350333-foffkbn0g95pcee2t1ge2tviv4hiumu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvxVJyzCKf4nAEQ7rHArHJnEdLfx3KsOg',
    appId: '1:707266350333:ios:854db7dabecf233bbdc294',
    messagingSenderId: '707266350333',
    projectId: 'marketapp-3f58d',
    storageBucket: 'marketapp-3f58d.appspot.com',
    androidClientId: '707266350333-gr36kievre56dg23cfji6gccg56ah10g.apps.googleusercontent.com',
    iosClientId: '707266350333-foffkbn0g95pcee2t1ge2tviv4hiumu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesApp',
  );
}
